#!/bin/bash

MAIN_PKGS(){

model=$(lscpu | grep 'Model name')

case "$model" in
    *Intel*) GPUDRE="xf86-video-intel" ;;
    *AMD*) GPUDRE="xf86-video-amdgpu";;	
esac

printf "$GPUDRE"

sudo xbps-install -Syu -u xbps && sudo xbps-install -Syu
sudo xbps-install -Syu mesa-dri bspwm sxhkd polybar papirus-icon-theme arc-theme udisks2 \
elogind mpv chromium firefox qbittorrent gvfs-mtp Thunar thunar-archive-plugin tree gvfs file-roller \
neofetch i3lock nitrogen curl ntfs-3g picom bluez blueman pipewire libspa-bluetooth pavucontrol rofi \
torbrowser-launcher telegram-desktop github-cli yt-dlp polkit-gnome gnome-calculator scrot eog evince \
kitty wget mousepad xorg-minimal xrandr xsetroot xdg-user-dirs $GPUDRE network-manager-applet xz \
os-prober lm_sensors brightnessctl zsh zsh-syntax-highlighting zsh-autosuggestions	
}

START_SERVICES(){

sudo ln -s /etc/sv/bluetoothd /var/service
sudo ln -s /etc/sv/polkitd /var/service
#sudo ln -s /etc/sv/rtkit /var/service
sudo ln -s /etc/sv/elogind /var/service
sudo ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/
sudo gpasswd -a $USER video
sudo xbps-reconfigure -f fontconfig
#sudo echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
#sudo grub-mkconfig -o /boot/grub/grub.cfg

#sudo mkdir /etc/X11/xorg.conf.d
#sudo touch /etc/X11/xorg.conf.d/30-touchpad.conf
#sudo echo '
#Section "InputClass"
#    Identifier "touchpad"
#    Driver "libinput"
#   MatchIsTouchpad "on"
#    Option "Tapping" "on"
#    Option "TappingButtonMap" "lmr"
#EndSection ' >> /etc/X11/xorg.conf.d/30-touchpad.conf


#sudo echo "load-module module-switch-on-connect" >> /etc/pulse/default.pa 
#sudo echo "echo 0 > /sys/class/backlight/amdgpu_bl0/brightness" > /etc/rc.local
#(do not run) sudo xbps-install mesa-vaapi mesa-vdpau
#sudo echo "blacklist nouveau" > /usr/lib/modprobe.d/blacklist.conf
#sudo touch /etc/modprobe.d/nouveau_blacklist.conf 
#sudo echo "blacklist nouveau" > /etc/modprobe.d/nouveau_blacklist.conf
#KE_VERN=$(uname -r | cut -d. -f-2) 
#sudo xbps-reconfigure -f linux${KE_VERN}
}



CNWR_CY() {
chmod +x .config/bspwm/bspwmrc && chmod +x .config/polybar/* && chmod +x .config/rofi/*
cp -r .config .xinitrc .zshrc .fonts /$HOME/ 
fc-cache -fv

}







REBOOT_CASE() { 
clear && /bin/echo -e '\n\n' "\e[1;32mREBOOTING NOW......\e[0m"
sleep 1
clear && /bin/echo -e '\n\n' "\e[1;31mEXITING......\e[0m" 
sudo reboot
}


#runfunctions

MAIN_PKGS 
START_SERVICES
CNWR_CY
REBOOT_CASE
























