#! /bin/sh

xset dpms 0 0 120 & 
/usr/libexec/polkit-gnome-authentication-agent-1 &
pipewire &
pipewire-pulse &
#picom -f &
picom --config $HOME/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr
nm-applet &
blueman-applet &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
#feh --bg-fill /$HOME/.config/d.jpg &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding            30
bspc config bottom_padding         10
bspc config left_padding           10
bspc config right_padding          10
#bspc config top_padding            40
#bspc config bottom_padding         30
#bspc config left_padding           20
#bspc config right_padding          20



bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
wmname compiz &

bspc config normal_border_color    "#2E3440"
bspc config active_border_color    "#81A1C1"
bspc config focused_border_color   "#81A1C1"
bspc config split_ratio            0.52
bspc config borderless_monocle     false
bspc config gapless_monocle        true
bspc config single_monocle         true
bspc config pointer_modifier       mod4
bspc config pointer_action1        move
bspc config pointer_action2        resize_corner
bspc config focus_follows_pointer  true
